version: 2
jobs:
  build:
    working_directory: ~/webapp
    filters: 
      branches:
        only:
          - A7
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            sudo apt-get update 
            sudo apt-get install -y python-pip
      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cd codedeploy_artifact
            cp ../infrastructure/aws/codedeploy/*.sh .
            cp ../cloudwatch-config.json .
            cp ../appspec.yml .
            cp ../webapp/target/demo-0.0.1-SNAPSHOT.jar .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip .
            rm *.yml *.sh *.jar *.json
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp --recursive codedeploy_artifact s3://${CODE_DEPLOY_S3_BUCKET}
      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment \
              --region ${AWS_REGION} \
              --output json \
              --application-name ${CODEDEPLOY_APPLICATION_NAME} \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name ${CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME} \
              --description "CSYE6225 -CodeDeploy"
              --revision s3-location={bucket=${CODE_DEPLOY_S3_BUCKET},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip}
